# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  labels:
    awsblueprints.io/environment: dev
    awsblueprints.io/provider: aws
    serverless.awsblueprints.io/app: sns-sqs-lambda-s3
  name: xsnssqslambdas3.awsblueprints.io
spec:
  compositeTypeRef:
    apiVersion: awsblueprints.io/v1alpha1
    kind: XServerlessApp
  mode: Pipeline
  pipeline:
  - functionRef:
      name: function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      patchSets:
      - name: common-fields-composition
        patches:
        - fromFieldPath: spec.resourceConfig
          toFieldPath: spec.resourceConfig
          type: FromCompositeFieldPath
      - name: common-lambda
        patches:
        - fromFieldPath: status.bucketName
          policy:
            fromFieldPath: Required
            toFieldPath: MergeObjects
          toFieldPath: spec.envVariables[APP__CONFIG__DESTINATIONBUCKET]
          type: FromCompositeFieldPath
        - fromFieldPath: status.bucketName
          policy:
            fromFieldPath: Required
            toFieldPath: MergeObjects
          toFieldPath: spec.envVariables[APP__CONFIG__DESTINATIONQUEUE]
          type: FromCompositeFieldPath
      resources:
      - base:
          apiVersion: awsblueprints.io/v1alpha1
          kind: XFanout
          spec:
            compositionSelector:
              matchLabels:
                awsblueprints.io/environment: dev
                awsblueprints.io/provider: aws
        name: sns-sqs
        patches:
        - patchSetName: common-fields-composition
          type: PatchSet
        - fromFieldPath: status.queueArn
          toFieldPath: status.sourceQueueArn
          type: ToCompositeFieldPath
        - fromFieldPath: status.keyName
          toFieldPath: spec.encryptionKey
          type: FromCompositeFieldPath
      - base:
          apiVersion: awsblueprints.io/v1alpha1
          kind: EventSourceMapping
          spec:
            compositionSelector:
              matchLabels:
                esm.awsblueprints.io/service: sqs
        name: processor-event-source
        patches:
        - patchSetName: common-fields-composition
          type: PatchSet
        - fromFieldPath: status.processorFuncName
          policy:
            fromFieldPath: Required
          toFieldPath: spec.funcName
          type: FromCompositeFieldPath
        - fromFieldPath: status.sourceQueueArn
          policy:
            fromFieldPath: Required
          toFieldPath: spec.sourceArn
          type: FromCompositeFieldPath
      - base:
          apiVersion: awsblueprints.io/v1alpha1
          kind: XLambdaFunction
          spec:
            compositionSelector:
              matchLabels:
                awsblueprints.io/environment: dev
                awsblueprints.io/provider: aws
                awsblueprints.io/type: zip
            envVariables:
              APP__CONFIG__PROCESSOR: "TRUE"
            handler: main
            resourceConfig:
              providerConfigName: aws-provider-config
              region: us-west-2
            runTime: go1.x
        name: processor-lambda
        patches:
        - patchSetName: common-fields-composition
          type: PatchSet
        - patchSetName: common-lambda
          type: PatchSet
        - fromFieldPath: spec.bucketName
          toFieldPath: spec.bucketName
          type: FromCompositeFieldPath
        - fromFieldPath: spec.bucketKey
          toFieldPath: spec.bucketKey
          type: FromCompositeFieldPath
        - fromFieldPath: spec.memorySize
          toFieldPath: spec.memorySize
          type: FromCompositeFieldPath
        - fromFieldPath: metadata.name
          toFieldPath: metadata.name
          transforms:
          - string:
              fmt: '%s-processor'
              type: Format
            type: string
          type: FromCompositeFieldPath
        - fromFieldPath: status.functionRoleName
          toFieldPath: status.processorRoleName
          type: ToCompositeFieldPath
        - fromFieldPath: status.functionName
          toFieldPath: status.processorFuncName
          type: ToCompositeFieldPath
        - fromFieldPath: status.functionRoleArn
          toFieldPath: status.accountNumber
          transforms:
          - string:
              regexp:
                group: 1
                match: arn:aws:iam::(\d+):.*
              type: Regexp
            type: string
          type: ToCompositeFieldPath
      - base:
          apiVersion: awsblueprints.io/v1alpha1
          kind: XObjectStorage
          metadata:
            name: standard-object-storage
          spec:
            compositionSelector:
              matchLabels:
                awsblueprints.io/environment: dev
                awsblueprints.io/provider: aws
                s3.awsblueprints.io/configuration: standard
        name: bucket
        patches:
        - patchSetName: common-fields-composition
          type: PatchSet
        - fromFieldPath: status.bucketName
          toFieldPath: status.bucketName
          type: ToCompositeFieldPath
        - fromFieldPath: status.bucketArn
          toFieldPath: status.bucketArn
          type: ToCompositeFieldPath
      - base:
          apiVersion: awsblueprints.io/v1alpha1
          kind: IAMPolicy
          spec:
            compositionSelector:
              matchLabels:
                awsblueprints.io/environment: dev
                awsblueprints.io/provider: aws
                iam.awsblueprints.io/policy-type: write
                iam.awsblueprints.io/service: s3
        name: processor-bucket-policy
        patches:
        - patchSetName: common-fields-composition
          type: PatchSet
        - fromFieldPath: status.processorRoleName
          toFieldPath: spec.roleName
          type: FromCompositeFieldPath
        - fromFieldPath: status.bucketArn
          toFieldPath: spec.resourceArn
          type: FromCompositeFieldPath
      - base:
          apiVersion: awsblueprints.io/v1alpha1
          kind: IAMPolicy
          spec:
            compositionSelector:
              matchLabels:
                awsblueprints.io/environment: dev
                awsblueprints.io/provider: aws
                iam.awsblueprints.io/policy-type: read
                iam.awsblueprints.io/service: sqs
        name: processor-sqs-policy
        patches:
        - patchSetName: common-fields-composition
          type: PatchSet
        - fromFieldPath: status.processorRoleName
          toFieldPath: spec.roleName
          type: FromCompositeFieldPath
        - fromFieldPath: status.sourceQueueArn
          toFieldPath: spec.resourceArn
          type: FromCompositeFieldPath
      - base:
          apiVersion: awsblueprints.io/v1alpha1
          kind: XEncryptionKey
          spec:
            compositionSelector:
              matchLabels:
                awsblueprints.io/environment: dev
                awsblueprints.io/provider: aws
        name: kms-key
        patches:
        - patchSetName: common-fields-composition
          type: PatchSet
        - fromFieldPath: status.keyArn
          toFieldPath: status.kmsKeyArn
          type: ToCompositeFieldPath
        - fromFieldPath: status.keyName
          toFieldPath: status.keyName
          type: ToCompositeFieldPath
        - combine:
            strategy: string
            string:
              fmt: |
                {
                  "Version": "2012-10-17",
                  "Statement": [
                    {
                      "Effect": "Allow",
                      "Principal": {"AWS": "arn:aws:iam::%s:root"},
                      "Action": "kms:*",
                      "Resource": "*"
                    },
                    {
                      "Effect": "Allow",
                      "Principal": {
                          "Service": "sns.amazonaws.com"
                      },
                      "Action": [
                          "kms:Decrypt",
                          "kms:GenerateDataKey*"
                      ],
                      "Resource": "*"
                    }
                  ]
                }
            variables:
            - fromFieldPath: status.accountNumber
          policy:
            fromFieldPath: Required
          toFieldPath: spec.policy
          type: CombineFromComposite
      - base:
          apiVersion: awsblueprints.io/v1alpha1
          kind: IAMPolicy
          spec:
            compositionSelector:
              matchLabels:
                awsblueprints.io/environment: dev
                awsblueprints.io/provider: aws
                iam.awsblueprints.io/policy-type: read
                iam.awsblueprints.io/service: kms
        name: processor-kms-policy
        patches:
        - patchSetName: common-fields-composition
          type: PatchSet
        - fromFieldPath: status.processorRoleName
          toFieldPath: spec.roleName
          type: FromCompositeFieldPath
        - fromFieldPath: status.kmsKeyArn
          toFieldPath: spec.resourceArn
          type: FromCompositeFieldPath
    step: patch-and-transform
