# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  labels:
    awsblueprints.io/environment: dev
    awsblueprints.io/provider: aws
    s3.awsblueprints.io/configuration: standard
  name: s3bucket.awsblueprints.io
spec:
  compositeTypeRef:
    apiVersion: awsblueprints.io/v1alpha1
    kind: XObjectStorage
  mode: Pipeline
  pipeline:
  - functionRef:
      name: function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      patchSets:
      - name: common-fields
        patches:
        - fromFieldPath: spec.resourceConfig.deletionPolicy
          toFieldPath: spec.deletionPolicy
          type: FromCompositeFieldPath
        - fromFieldPath: spec.resourceConfig.region
          toFieldPath: spec.forProvider.region
          type: FromCompositeFieldPath
        - fromFieldPath: spec.resourceConfig.providerConfigName
          toFieldPath: spec.providerConfigRef.name
          type: FromCompositeFieldPath
        - fromFieldPath: spec.resourceConfig.tags
          policy:
            toFieldPath: MergeObjects
          toFieldPath: spec.forProvider.tags
          type: FromCompositeFieldPath
        - fromFieldPath: spec.resourceConfig.name
          toFieldPath: metadata.annotations[crossplane.io/external-name]
          type: FromCompositeFieldPath
        - fromFieldPath: metadata.name
          toFieldPath: metadata.name
          transforms:
          - string:
              fmt: bucket-%s
              type: Format
            type: string
          type: FromCompositeFieldPath
      resources:
      - base:
          apiVersion: s3.aws.upbound.io/v1beta1
          kind: Bucket
          spec:
            deletionPolicy: Delete
            forProvider:
              forceDestroy: true
              region: us-west-2
            writeConnectionSecretToRef:
              namespace: crossplane-system
        connectionDetails:
        - fromFieldPath: status.atProvider.id
          name: bucketName
          type: FromFieldPath
        name: s3-bucket
        patches:
        - patchSetName: common-fields
          type: PatchSet
        - fromFieldPath: status.atProvider.id
          toFieldPath: status.bucketName
          type: ToCompositeFieldPath
        - fromFieldPath: status.atProvider.id
          toFieldPath: status.bucketArn
          transforms:
          - string:
              fmt: arn:aws:s3:::%s
              type: Format
            type: string
          type: ToCompositeFieldPath
      - base:
          apiVersion: s3.aws.upbound.io/v1beta1
          kind: BucketPublicAccessBlock
          spec:
            deletionPolicy: Delete
            forProvider:
              blockPublicAcls: true
              blockPublicPolicy: true
              bucketSelector:
                matchControllerRef: true
              ignorePublicAcls: true
              restrictPublicBuckets: true
        name: s3-blockpublicaccess
        patches:
        - fromFieldPath: spec.resourceConfig.region
          toFieldPath: spec.forProvider.region
          type: FromCompositeFieldPath
        - fromFieldPath: spec.resourceConfig.providerConfigName
          toFieldPath: spec.providerConfigRef.name
          type: FromCompositeFieldPath
      - base:
          apiVersion: s3.aws.upbound.io/v1beta1
          kind: BucketServerSideEncryptionConfiguration
          spec:
            deletionPolicy: Delete
            forProvider:
              bucketSelector:
                matchControllerRef: true
              rule:
              - applyServerSideEncryptionByDefault:
                - sseAlgorithm: AES256
        name: s3-serversideencryption
        patches:
        - fromFieldPath: spec.resourceConfig.providerConfigName
          toFieldPath: spec.providerConfigRef.name
          type: FromCompositeFieldPath
        - fromFieldPath: spec.resourceConfig.region
          toFieldPath: spec.forProvider.region
          type: FromCompositeFieldPath
    step: patch-and-transform
  writeConnectionSecretsToNamespace: crossplane-system
