# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  labels:
    awsblueprints.io/environment: dev
    awsblueprints.io/provider: aws
    cloudwatch.awsblueprints.io/logs: subscriptionfilter
    cloudwatch.awsblueprints.io/service: cloudwatch-logs
  name: subscriptionfilter.upbound.awsblueprints.io
spec:
  compositeTypeRef:
    apiVersion: awsblueprints.io/v1alpha1
    kind: XSubscriptionFilter
  mode: Pipeline
  pipeline:
  - functionRef:
      name: function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      patchSets:
      - name: common-fields
        patches:
        - fromFieldPath: spec.resourceConfig.deletionPolicy
          toFieldPath: spec.deletionPolicy
          type: FromCompositeFieldPath
        - fromFieldPath: spec.resourceConfig.region
          toFieldPath: spec.forProvider.region
          type: FromCompositeFieldPath
        - fromFieldPath: spec.resourceConfig.tags
          policy:
            toFieldPath: MergeObjects
          toFieldPath: spec.forProvider.tags
          type: FromCompositeFieldPath
        - fromFieldPath: spec.resourceConfig.name
          toFieldPath: metadata.annotations[crossplane.io/external-name]
          type: FromCompositeFieldPath
        - fromFieldPath: spec.resourceConfig.providerConfigName
          toFieldPath: spec.providerConfigRef.name
          type: FromCompositeFieldPath
        - fromFieldPath: metadata.name
          toFieldPath: metadata.name
          transforms:
          - string:
              fmt: subscriptionfilter-%s
              type: Format
            type: string
          type: FromCompositeFieldPath
      resources:
      - base:
          apiVersion: cloudwatchlogs.aws.upbound.io/v1beta1
          kind: SubscriptionFilter
          spec:
            forProvider: {}
        name: subscriptionfilter
        patches:
        - fromFieldPath: spec.forProvider
          toFieldPath: spec.forProvider
          type: FromCompositeFieldPath
        - patchSetName: common-fields
          type: PatchSet
        - fromFieldPath: metadata.name
          toFieldPath: spec.forProvider.name
          transforms:
          - string:
              fmt: subscriptionfilter-%s
              type: Format
            type: string
          type: FromCompositeFieldPath
    step: patch-and-transform
