# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  labels:
    awsblueprints.io/environment: dev
    awsblueprints.io/provider: aws
  name: table.dynamodb.awsblueprints.io
spec:
  compositeTypeRef:
    apiVersion: awsblueprints.io/v1alpha1
    kind: XDynamoDBTable
  mode: Pipeline
  pipeline:
  - functionRef:
      name: function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      patchSets:
      - name: common-fields
        patches:
        - fromFieldPath: spec.resourceConfig.providerConfigName
          toFieldPath: spec.providerConfigRef.name
          type: FromCompositeFieldPath
        - fromFieldPath: spec.resourceConfig.region
          toFieldPath: spec.forProvider.region
          type: FromCompositeFieldPath
        - fromFieldPath: spec.resourceConfig.name
          toFieldPath: metadata.annotations[crossplane.io/external-name]
          type: FromCompositeFieldPath
      resources:
      - base:
          apiVersion: dynamodb.aws.upbound.io/v1beta1
          kind: Table
          spec:
            forProvider: {}
            writeConnectionSecretToRef:
              namespace: crossplane-system
        connectionDetails:
        - fromFieldPath: status.atProvider.id
          name: tableName
          type: FromFieldPath
        name: table
        patches:
        - patchSetName: common-fields
          type: PatchSet
        - fromFieldPath: spec.dynamoConfig.attribute
          policy:
            toFieldPath: MergeObjectsAppendArrays
          toFieldPath: spec.forProvider.attribute
          type: FromCompositeFieldPath
        - fromFieldPath: spec.resourceConfig.tags
          policy:
            toFieldPath: MergeObjects
          toFieldPath: spec.forProvider.tags
          type: FromCompositeFieldPath
        - fromFieldPath: spec.dynamoConfig.hashKey
          toFieldPath: spec.forProvider.hashKey
          type: FromCompositeFieldPath
        - fromFieldPath: spec.dynamoConfig.billingMode
          toFieldPath: spec.forProvider.billingMode
          type: FromCompositeFieldPath
        - fromFieldPath: spec.dynamoConfig.rangeKey
          toFieldPath: spec.forProvider.rangeKey
          type: FromCompositeFieldPath
        - fromFieldPath: spec.dynamoConfig.readCapacity
          toFieldPath: spec.forProvider.readCapacity
          type: FromCompositeFieldPath
        - fromFieldPath: spec.dynamoConfig.writeCapacity
          toFieldPath: spec.forProvider.writeCapacity
          type: FromCompositeFieldPath
        - fromFieldPath: spec.dynamoConfig.globalSecondaryIndex
          policy:
            toFieldPath: MergeObjects
          toFieldPath: spec.forProvider.globalSecondaryIndex
          type: FromCompositeFieldPath
        - fromFieldPath: spec.dynamoConfig.localSecondaryIndex
          policy:
            toFieldPath: MergeObjects
          toFieldPath: spec.forProvider.localSecondaryIndex
          type: FromCompositeFieldPath
        - fromFieldPath: status.atProvider.id
          toFieldPath: status.tableName
          type: ToCompositeFieldPath
        - fromFieldPath: status.atProvider.arn
          toFieldPath: status.tableArn
          type: ToCompositeFieldPath
    step: patch-and-transform
  writeConnectionSecretsToNamespace: crossplane-system
