# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  labels:
    awsblueprints.io/environment: dev
    awsblueprints.io/provider: aws
  name: xencryptionkeys-kms.awsblueprints.io
spec:
  compositeTypeRef:
    apiVersion: awsblueprints.io/v1alpha1
    kind: XEncryptionKey
  mode: Pipeline
  pipeline:
  - functionRef:
      name: function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      patchSets:
      - name: common-fields
        patches:
        - fromFieldPath: spec.resourceConfig.deletionPolicy
          toFieldPath: spec.deletionPolicy
          type: FromCompositeFieldPath
        - fromFieldPath: spec.resourceConfig.region
          toFieldPath: spec.forProvider.region
          type: FromCompositeFieldPath
        - fromFieldPath: spec.resourceConfig.providerConfigName
          toFieldPath: spec.providerConfigRef.name
          type: FromCompositeFieldPath
      resources:
      - base:
          apiVersion: kms.aws.upbound.io/v1beta1
          kind: Key
          spec:
            forProvider:
              deletionWindowInDays: 10
              description: for use with this account
        name: key
        patches:
        - patchSetName: common-fields
          type: PatchSet
        - fromFieldPath: spec.policy
          toFieldPath: spec.forProvider.policy
          type: FromCompositeFieldPath
        - fromFieldPath: status.atProvider.arn
          toFieldPath: status.keyArn
          type: ToCompositeFieldPath
        - fromFieldPath: status.atProvider.keyId
          toFieldPath: status.keyId
          type: ToCompositeFieldPath
        - fromFieldPath: spec.resourceConfig.tags
          policy:
            toFieldPath: MergeObjects
          toFieldPath: spec.forProvider.tags
          type: FromCompositeFieldPath
      - base:
          apiVersion: kms.aws.upbound.io/v1beta1
          kind: Alias
          spec:
            forProvider: {}
        name: alais
        patches:
        - patchSetName: common-fields
          type: PatchSet
        - fromFieldPath: status.keyId
          policy:
            fromFieldPath: Required
          toFieldPath: spec.forProvider.targetKeyId
          type: FromCompositeFieldPath
        - fromFieldPath: status.atProvider.id
          toFieldPath: status.keyName
          type: ToCompositeFieldPath
    step: patch-and-transform
