# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  labels:
    awsblueprints.io/environment: dev
    awsblueprints.io/provider: aws
    iam.awsblueprints.io/policy-type: write
    iam.awsblueprints.io/service: dynamodb
  name: write-dynamodb.iampolicy.awsblueprints.io
spec:
  compositeTypeRef:
    apiVersion: awsblueprints.io/v1alpha1
    kind: IAMPolicy
  mode: Pipeline
  pipeline:
  - functionRef:
      name: function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      patchSets:
      - name: common-fields
        patches:
        - fromFieldPath: spec.resourceConfig.deletionPolicy
          toFieldPath: spec.deletionPolicy
          type: FromCompositeFieldPath
        - fromFieldPath: spec.resourceConfig.providerConfigName
          toFieldPath: spec.providerConfigRef.name
          type: FromCompositeFieldPath
        - fromFieldPath: metadata.name
          toFieldPath: metadata.name
          transforms:
          - string:
              fmt: policy-dynamodb-write-%s
              type: Format
            type: string
          type: FromCompositeFieldPath
      resources:
      - base:
          apiVersion: iam.aws.upbound.io/v1beta1
          kind: Policy
          spec:
            deletionPolicy: Delete
            forProvider: {}
        name: write-policy
        patches:
        - patchSetName: common-fields
          type: PatchSet
        - fromFieldPath: spec.resourceConfig.tags
          policy:
            toFieldPath: MergeObjects
          toFieldPath: spec.forProvider.tags
          type: FromCompositeFieldPath
        - combine:
            strategy: string
            string:
              fmt: |
                {
                    "Version": "2012-10-17",
                    "Statement": [
                        {
                            "Sid": "ListAndDescribe",
                            "Effect": "Allow",
                            "Action": [
                                "dynamodb:List*",
                                "dynamodb:DescribeReservedCapacity*",
                                "dynamodb:DescribeLimits",
                                "dynamodb:DescribeTimeToLive"
                            ],
                            "Resource": [
                              "%s/*"
                            ]
                        },
                        {
                            "Sid": "SpecificTable",
                            "Effect": "Allow",
                            "Action": [
                                "dynamodb:BatchGet*",
                                "dynamodb:DescribeStream",
                                "dynamodb:DescribeTable",
                                "dynamodb:Query",
                                "dynamodb:Scan",
                                "dynamodb:BatchWrite*",
                                "dynamodb:CreateTable",
                                "dynamodb:Delete*",
                                "dynamodb:Update*",
                                "dynamodb:GetItem",
                                "dynamodb:PutItem"
                            ],
                            "Resource": [
                              "%s/*",
                              "%s"
                            ]
                        }
                    ]
                }
            variables:
            - fromFieldPath: spec.resourceArn
            - fromFieldPath: spec.resourceArn
            - fromFieldPath: spec.resourceArn
          toFieldPath: spec.forProvider.policy
          type: CombineFromComposite
      - base:
          apiVersion: iam.aws.upbound.io/v1beta1
          kind: RolePolicyAttachment
          spec:
            deletionPolicy: Delete
            forProvider:
              policyArnSelector:
                matchControllerRef: true
        name: policy-attachment
        patches:
        - patchSetName: common-fields
          type: PatchSet
        - fromFieldPath: spec.roleName
          toFieldPath: spec.forProvider.role
          type: FromCompositeFieldPath
    step: patch-and-transform
