# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  labels:
    awsblueprints.io/environment: dev
    awsblueprints.io/provider: aws
    iam.awsblueprints.io/policy-type: write
    iam.awsblueprints.io/service: firehose-s3
  name: write-firehose-s3.iampolicy.awsblueprints.io
spec:
  compositeTypeRef:
    apiVersion: awsblueprints.io/v1alpha1
    kind: IAMPolicy
  mode: Pipeline
  pipeline:
  - functionRef:
      name: function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      patchSets:
      - name: common-fields
        patches:
        - fromFieldPath: spec.resourceConfig.deletionPolicy
          toFieldPath: spec.deletionPolicy
          type: FromCompositeFieldPath
        - fromFieldPath: spec.resourceConfig.providerConfigName
          toFieldPath: spec.providerConfigRef.name
          type: FromCompositeFieldPath
        - fromFieldPath: metadata.name
          toFieldPath: metadata.name
          transforms:
          - string:
              fmt: policy-s3-write-firehose-%s
              type: Format
            type: string
          type: FromCompositeFieldPath
      resources:
      - base:
          apiVersion: iam.aws.upbound.io/v1beta1
          kind: Policy
          spec:
            deletionPolicy: Delete
            forProvider: {}
        name: write-policy
        patches:
        - patchSetName: common-fields
          type: PatchSet
        - fromFieldPath: spec.resourceConfig.tags
          policy:
            toFieldPath: MergeObjects
          toFieldPath: spec.forProvider.tags
          type: FromCompositeFieldPath
        - combine:
            strategy: string
            string:
              fmt: |
                {
                  "Version": "2012-10-17",
                  "Statement": [
                    {
                        "Action": [
                            "s3:AbortMultipartUpload",
                            "s3:GetBucketLocation",
                            "s3:GetObject",
                            "s3:ListBucket",
                            "s3:ListBucketMultipartUploads",
                            "s3:PutObject"
                        ],
                        "Resource": [
                            "%s",
                            "%s/*"
                        ],
                        "Effect": "Allow"
                    }
                  ]
                }
            variables:
            - fromFieldPath: spec.resourceArn
            - fromFieldPath: spec.resourceArn
          toFieldPath: spec.forProvider.policy
          type: CombineFromComposite
      - base:
          apiVersion: iam.aws.upbound.io/v1beta1
          kind: RolePolicyAttachment
          spec:
            deletionPolicy: Delete
            forProvider:
              policyArnSelector:
                matchControllerRef: true
        name: policy-attachment
        patches:
        - patchSetName: common-fields
          type: PatchSet
        - fromFieldPath: spec.roleName
          toFieldPath: spec.forProvider.role
          type: FromCompositeFieldPath
    step: patch-and-transform
