# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  labels:
    awsblueprints.io/environment: dev
    awsblueprints.io/provider: aws
  name: xdynamoirsa.awsblueprints.io
spec:
  compositeTypeRef:
    apiVersion: awsblueprints.io/v1alpha1
    kind: XDynamoIRSA
  mode: Pipeline
  pipeline:
  - functionRef:
      name: function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      patchSets:
      - name: common-fields-composition
        patches:
        - fromFieldPath: spec.resourceConfig
          toFieldPath: spec.resourceConfig
          type: FromCompositeFieldPath
      resources:
      - base:
          apiVersion: awsblueprints.io/v1alpha1
          kind: XDynamoDBTable
        connectionDetails:
        - fromFieldPath: status.tableName
          name: tableName
          type: FromFieldPath
        name: dynamodbtable
        patches:
        - patchSetName: common-fields-composition
          type: PatchSet
        - fromFieldPath: spec.dynamoConfig
          toFieldPath: spec.dynamoConfig
          type: FromCompositeFieldPath
        - fromFieldPath: status.tableName
          toFieldPath: status.tableName
          type: ToCompositeFieldPath
        - fromFieldPath: status.tableArn
          toFieldPath: status.tableArn
          type: ToCompositeFieldPath
      - base:
          apiVersion: awsblueprints.io/v1alpha1
          kind: XIRSA
        name: irsa
        patches:
        - patchSetName: common-fields-composition
          type: PatchSet
        - fromFieldPath: metadata.labels[crossplane.io/claim-name]
          toFieldPath: spec.serviceAccountName
          type: FromCompositeFieldPath
        - fromFieldPath: status.roleName
          toFieldPath: status.roleName
          type: ToCompositeFieldPath
      - base:
          apiVersion: awsblueprints.io/v1alpha1
          kind: IAMPolicy
          spec:
            compositionSelector:
              matchLabels:
                awsblueprints.io/environment: dev
                awsblueprints.io/provider: aws
                iam.awsblueprints.io/policy-type: write
                iam.awsblueprints.io/service: dynamodb
        name: irsa-dynamo-policy
        patches:
        - patchSetName: common-fields-composition
          type: PatchSet
        - fromFieldPath: status.roleName
          toFieldPath: spec.roleName
          type: FromCompositeFieldPath
        - fromFieldPath: status.tableArn
          toFieldPath: spec.resourceArn
          type: FromCompositeFieldPath
    step: patch-and-transform
  writeConnectionSecretsToNamespace: crossplane-system
