# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  labels:
    awsblueprints.io/environment: dev
    awsblueprints.io/provider: aws
    notification.awsblueprints.io/sns-config: cloudwatch
    notification.awsblueprints.io/type: standard
  name: sns.notification.upbound.awsblueprints.io
spec:
  compositeTypeRef:
    apiVersion: awsblueprints.io/v1alpha1
    kind: XNotification
  mode: Pipeline
  pipeline:
  - functionRef:
      name: function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      patchSets:
      - name: common-fields
        patches:
        - fromFieldPath: spec.resourceConfig.deletionPolicy
          toFieldPath: spec.deletionPolicy
          type: FromCompositeFieldPath
        - fromFieldPath: spec.resourceConfig.providerConfigName
          toFieldPath: spec.providerConfigRef.name
          type: FromCompositeFieldPath
        - fromFieldPath: spec.resourceConfig.name
          toFieldPath: metadata.annotations[crossplane.io/external-name]
          type: FromCompositeFieldPath
        - fromFieldPath: metadata.name
          toFieldPath: metadata.name
          transforms:
          - string:
              fmt: topic-%s
              type: Format
            type: string
          type: FromCompositeFieldPath
      resources:
      - base:
          apiVersion: iam.aws.upbound.io/v1beta1
          kind: Role
          metadata:
            labels:
              testing.awsblueprints.io/name: sns-feedback
          spec:
            deletionPolicy: Delete
            forProvider:
              assumeRolePolicy: |
                {
                  "Version": "2012-10-17",
                  "Statement": [
                    {
                      "Effect": "Allow",
                      "Principal": {
                        "Service": "sns.amazonaws.com"
                      },
                      "Action": "sts:AssumeRole"
                    }
                  ]
                }
        name: sns-feedback
        patches:
        - patchSetName: common-fields
          type: PatchSet
        - fromFieldPath: metadata.name
          toFieldPath: metadata.name
          transforms:
          - string:
              fmt: sns-feedback-%s
              type: Format
            type: string
          type: FromCompositeFieldPath
        - fromFieldPath: spec.resourceConfig.tags
          policy:
            toFieldPath: MergeObjects
          toFieldPath: spec.forProvider.tags
          type: FromCompositeFieldPath
      - base:
          apiVersion: iam.aws.upbound.io/v1beta1
          kind: RolePolicyAttachment
          spec:
            deletionPolicy: Delete
            forProvider:
              policyArn: arn:aws:iam::aws:policy/service-role/AmazonSNSRole
              roleSelector:
                matchControllerRef: true
        name: sns-feedback-policy-attachment
        patches:
        - patchSetName: common-fields
          type: PatchSet
      - base:
          apiVersion: sns.aws.upbound.io/v1beta1
          kind: Topic
          spec:
            deletionPolicy: Delete
            forProvider:
              sqsFailureFeedbackRoleArnSelector:
                matchLabels:
                  testing.awsblueprints.io/name: sns-feedback
              sqsSuccessFeedbackRoleArnSelector:
                matchLabels:
                  testing.awsblueprints.io/name: sns-feedback
              sqsSuccessFeedbackSampleRate: 100
        name: sns
        patches:
        - patchSetName: common-fields
          type: PatchSet
        - fromFieldPath: spec.encryptionKey
          toFieldPath: spec.forProvider.kmsMasterKeyId
          type: FromCompositeFieldPath
        - fromFieldPath: metadata.name
          toFieldPath: spec.forProvider.displayName
          transforms:
          - string:
              fmt: managed by crossplane object %s
              type: Format
            type: string
          type: FromCompositeFieldPath
        - fromFieldPath: status.atProvider.arn
          toFieldPath: status.topicArn
          type: ToCompositeFieldPath
        - fromFieldPath: status.atProvider.id
          toFieldPath: status.topicId
          type: ToCompositeFieldPath
        - fromFieldPath: spec.resourceConfig.region
          toFieldPath: spec.forProvider.region
          type: FromCompositeFieldPath
        - fromFieldPath: spec.resourceConfig.tags
          policy:
            toFieldPath: MergeObjects
          toFieldPath: spec.forProvider.tags
          type: FromCompositeFieldPath
    step: patch-and-transform
